dist: trusty
sudo: required
language: go
go: "1.10"
services:
  - docker
install:
  - go build
script:
  - go get github.com/goreleaser/goreleaser
  - test -n "$TRAVIS_TAG" || goreleaser --skip-validate --skip-publish --snapshot

after_success:
  # We have a tag
  - test -n "$TRAVIS_TAG" && goreleaser

notifications:
  email: false
